### ISSUE TITLE
能否转载博主博客？

### ISSUE THREAD

**Issue by islishude** [Newt0n/newt0n.github.io#1]
想转载博主的博客到我们公司的微信公众号（区块链大学）上，希望能得到您的授权。

**Comment by Newt0n** [comment]
可以，麻烦带上文章域名链接就行 http://newton.sh

**Comment by Newt0n** [comment]
@isLishude 可以，麻烦带上文章域名链接就行 http://newton.sh

**Comment by islishude** [comment]
好的，我们会署名并且加上文章域名链接
